// Generated by scripts/build-packs.mjs from packs/*.json. Do not edit by hand.
window.CONNECTIONS_PACKS = [
 {
  "id": "ben",
  "name": "About Ben",
  "theme": "ben",
  "blurb": "Five puzzles GPT-5 wrote about me on September 29, 2025, after searching the web for my name and Pittsburgh. Saved from the live generator and played as-is.",
  "disclaimer": "Written by an AI from public web pages about Ben Collier, then saved. Nothing here was edited by hand except the puzzle titles.",
  "puzzles": [
   {
    "id": "ben-1",
    "title": "Pizza, Pogs and Kennywood",
    "intro": "",
    "generated": {
     "model": "gpt-5",
     "ts": "2025-09-30T03:13:36.179Z",
     "player": "Ben Collier",
     "location": "Pittsburgh, PA"
    },
    "explanation": "Built for Ben in Pittsburgh: we mixed a slice‑of‑life pizza set, a playful ’90s throwback, a single Steel City nod via Kennywood rides, and one techy curveball to keep the table guessing. It’s party‑friendly, quick to play, and sprinkled with local flavor and geeky delight.",
    "categories": [
     {
      "label": "PIZZA TOPPING HALL‑OF‑FAMERS",
      "words": [
       "PEPPERONI",
       "MUSHROOM",
       "SAUSAGE",
       "ONION"
      ],
      "explanation": "Friday‑night fuel for a friendly crowd; classic toppings Ben and pals can debate while the game heats up.",
      "color": "Yellow"
     },
     {
      "label": "’90S TOY CRAZE STARS",
      "words": [
       "TAMAGOTCHI",
       "FURBY",
       "POGS",
       "YO-YO"
      ],
      "explanation": "Nostalgia blast for anyone who traded slammers, fed pixel pets, or practiced Walk‑the‑Dog between bites of pizza.",
      "color": "Green"
     },
     {
      "label": "KENNYWOOD THRILL RIDES",
      "words": [
       "JACK RABBIT",
       "THUNDERBOLT",
       "EXTERMINATOR",
       "RACER"
      ],
      "explanation": "A hometown wink: iconic Pittsburgh‑area coasters Ben might recognize from summer days and yinz‑y chatter.",
      "color": "Blue"
     },
     {
      "label": "DATA WAREHOUSE HEAVY‑HITTERS",
      "words": [
       "SNOWFLAKE",
       "REDSHIFT",
       "BIGQUERY",
       "DATABRICKS"
      ],
      "explanation": "One brainy set for the tech‑curious—stack names you’ve seen powering dashboards and experiments.",
      "color": "Purple"
     }
    ],
    "recommendations": [
     {
      "title": "‘It’s back, better than ever’: Steel Curtain reopens at Kennywood (May 24, 2025)",
      "url": "https://www.wtae.com/article/west-mifflin-kennywood-steel-curtain-2025-reopening/64871480",
      "type": "article"
     },
     {
      "title": "Kennywood’s Steel Curtain reopening date announced (May 2025)",
      "url": "https://www.cbsnews.com/pittsburgh/news/kennywood-steel-curtain-opening-date-2025/",
      "type": "article"
     },
     {
      "title": "Tamagotchi Plaza announced for Nintendo Switch (June 27, 2025)",
      "url": "https://en.bandainamcoent.eu/tamagotchi/news/get-ready-set-shop-tamagotchi-plaza-launching-27-june-2025-nintendo-switch",
      "type": "article"
     },
     {
      "title": "Hasbro at Toy Fair 2025: Furby minis and more",
      "url": "https://newsroom.hasbro.com/news-releases/news-release-details/hasbro-playing-win-2025-toy-fairr-slate-new-product-reveals",
      "type": "article"
     },
     {
      "title": "New survey: Pepperoni is America’s favorite pizza topping (July 16, 2024)",
      "url": "https://www.bakemag.com/articles/19162-new-survey-finds-pepperoni-ranked-as-favorite-pizza-topping",
      "type": "article"
     },
     {
      "title": "Databricks teams up with OpenAI for enterprise AI models (Sept. 25, 2025)",
      "url": "https://www.reuters.com/business/databricks-openai-team-up-deliver-ai-models-enterprise-clients-2025-09-25/",
      "type": "article"
     }
    ]
   },
   {
    "id": "ben-2",
    "title": "Arcade Night",
    "intro": "",
    "generated": {
     "model": "gpt-5",
     "ts": "2025-09-30T02:57:05.976Z",
     "player": "Ben Collier",
     "location": "Pittsburgh, PA"
    },
    "explanation": "For Ben Collier in Pittsburgh, this Connections set mashes up hometown bites, pixel‑perfect nostalgia, game‑night favorites, and a cheeky wordplay twist—so the table can debate pierogies vs. Primanti, hum arcade jingles, trade sheep for wood, and flex palindrome brainpower, all in one friendly party round.",
    "categories": [
     {
      "label": "QUARTER‑MUNCHING ARCADE ICONS",
      "words": [
       "PAC-MAN",
       "GALAGA",
       "FROGGER",
       "CENTIPEDE"
      ],
      "explanation": "Cabinet classics that scream neon nostalgia—Ben and friends can almost hear the coin drop.",
      "color": "Yellow"
     },
     {
      "label": "PITTSBURGH SNACK LEGENDS",
      "words": [
       "PRIMANTI",
       "PIEROGI",
       "HEINZ",
       "KLONDIKE"
      ],
      "explanation": "Steel City comfort-food celebs—perfect for a Yinzer-friendly laugh and a hunger pang mid‑game.",
      "color": "Green"
     },
     {
      "label": "BOARD GAMES THAT SPARK FRIENDLY RIVALRY",
      "words": [
       "CATAN",
       "AZUL",
       "PANDEMIC",
       "SPLENDOR"
      ],
      "explanation": "Modern tabletop hits that turn a casual hang into a triumphant high‑five or a dramatic ‘rematch!’",
      "color": "Blue"
     },
     {
      "label": "PALINDROME WORDS",
      "words": [
       "KAYAK",
       "CIVIC",
       "RADAR",
       "LEVEL"
      ],
      "explanation": "Word‑nerd party trick: each reads the same forward and backward—simple to spot, sneaky to sort.",
      "color": "Purple"
     }
    ],
    "recommendations": [
     {
      "title": "Heinz History Center makes admission free for kids, expansion planned (2025)",
      "url": "https://www.axios.com/local/pittsburgh/2025/06/03/heinz-history-center-free-for-kids",
      "type": "article"
     },
     {
      "title": "Pittsburgh Pierogi Festival — May 17, 2025 (Official site)",
      "url": "https://pittsburghpierogifestival.com/",
      "type": "article"
     },
     {
      "title": "Bandai Namco: PAC‑MAN 45th Anniversary campaign and events (2025)",
      "url": "https://www.bandainamcoent.com/news/pac-man-45th-anniversary",
      "type": "article"
     },
     {
      "title": "Krispy Kreme celebrates PAC‑MAN’s 45th with free doughnuts (2025)",
      "url": "https://people.com/krispy-kreme-celebrating-pac-man-45th-anniversary-with-free-doughnuts-11732925",
      "type": "article"
     },
     {
      "title": "Catan 6th Edition launches for the game’s 30th anniversary (2025)",
      "url": "https://www.polygon.com/deals/555561/catan-sixth-edition-6e-seafarers-cities-knights-where-to-buy",
      "type": "article"
     }
    ]
   },
   {
    "id": "ben-3",
    "title": "The Experiment",
    "intro": "",
    "generated": {
     "model": "gpt-5",
     "ts": "2025-09-30T02:48:05.434Z",
     "player": "Ben Collier",
     "location": "Pittsburgh, PA"
    },
    "explanation": "Tailored for Ben Collier in Pittsburgh: three sets draw on public-facing work in analytics, experimentation, and learning science (edtech and teaching), plus one local set nods to the Three Rivers. The mix targets both your product/education focus and your Pittsburgh roots while keeping categories distinct from prior puzzles.",
    "categories": [
     {
      "label": "Feature Engineering Techniques",
      "words": [
       "SCALING",
       "BINNING",
       "IMPUTATION",
       "ENCODING"
      ],
      "explanation": "Practical preprocessing steps often taught and applied in business analytics and ML pipelines.",
      "color": "Yellow"
     },
     {
      "label": "Product Experimentation Methods",
      "words": [
       "CUPED",
       "SWITCHBACK",
       "HOLDOUT",
       "BANDIT"
      ],
      "explanation": "Variance reduction and test designs you likely use when guiding product analytics and experiments in edtech/tech.",
      "color": "Green"
     },
     {
      "label": "Learning Assessment Models (EdTech)",
      "words": [
       "IRT",
       "ELO",
       "GLICKO",
       "BKT"
      ],
      "explanation": "Core models for estimating learner skill and item difficulty—relevant to language testing and adaptive learning.",
      "color": "Blue"
     },
     {
      "label": "Pittsburgh Rivers",
      "words": [
       "ALLEGHENY",
       "MONONGAHELA",
       "OHIO",
       "YOUGHIOGHENY"
      ],
      "explanation": "Waterways around Point State Park—the local context for a Pittsburgh-based player.",
      "color": "Purple"
     }
    ],
    "recommendations": [
     {
      "title": "Optimizely: CUPED (variance reduction) explained and implemented (2025)",
      "url": "https://support.optimizely.com/hc/en-us/articles/33424529987597-CUPED-Controlled-experiment-Using-Pre-Experiment-Data",
      "type": "article"
     },
     {
      "title": "Statsig blog: Switchback experiments—overview and considerations",
      "url": "https://www.statsig.com/blog/switchback-experiments",
      "type": "article"
     },
     {
      "title": "AutoIRT for the Duolingo English Test (2024)",
      "url": "https://arxiv.org/abs/2409.08823",
      "type": "article"
     },
     {
      "title": "Feature engineering tips (2025 overview)",
      "url": "https://www.techtarget.com/searchdatamanagement/feature/Top-5-feature-engineering-tips-for-better-models",
      "type": "article"
     },
     {
      "title": "Riverlife breaks ground on Allegheny Riverfront Park renovations (2025)",
      "url": "https://www.wesa.fm/arts-culture/2025-03-27/riverlife-allegheny-riverfront-park-renovations-groundbreaking",
      "type": "article"
     },
     {
      "title": "Ben Collier, PhD—Tepper Business Analytics hiring post (2025)",
      "url": "https://www.linkedin.com/posts/bcollierphd_apply-interfolio-activity-7305689417376018433-QdAz",
      "type": "article"
     }
    ]
   },
   {
    "id": "ben-4",
    "title": "The Data Stack",
    "intro": "",
    "generated": {
     "model": "gpt-5",
     "ts": "2025-09-30T02:01:36.297Z",
     "player": "Ben Collier",
     "location": "Pittsburgh, PA"
    },
    "explanation": "Tailoring this set for Ben Collier in Pittsburgh: public info shows you teach business analytics at CMU’s Tepper School and bring prior industry experience from a language-learning company and healthcare analytics, so the puzzle blends Python analytics tools, healthcare interoperability, and spaced-repetition systems—with just one local category for balance. ([poetsandquants.com](https://poetsandquants.com/2025/01/10/meet-carnegie-mellon-teppers-mba-class-of-2026/2/?utm_source=openai))",
    "categories": [
     {
      "label": "PITTSBURGH NEIGHBORHOODS",
      "words": [
       "OAKLAND",
       "SHADYSIDE",
       "BLOOMFIELD",
       "LAWRENCEVILLE"
      ],
      "explanation": "Four adjacent neighborhoods you likely see often around CMU and the East End—one local category for hometown flavor.",
      "color": "Yellow"
     },
     {
      "label": "PYTHON DATA STACK",
      "words": [
       "NUMPY",
       "PANDAS",
       "SEABORN",
       "SCIKIT-LEARN"
      ],
      "explanation": "Core Python libraries taught and used across business analytics and data science—highly relevant to your CMU teaching in analytics and staying current with tooling releases.",
      "color": "Green"
     },
     {
      "label": "HEALTH DATA STANDARDS",
      "words": [
       "FHIR",
       "HL7",
       "ICD",
       "SNOMED"
      ],
      "explanation": "Widely used clinical and claims/interoperability standards—useful context for analytics projects tied to healthcare data and interoperability testing updates.",
      "color": "Blue"
     },
     {
      "label": "SPACED REPETITION SYSTEMS",
      "words": [
       "ANKI",
       "LEITNER",
       "SUPERMEMO",
       "HALF-LIFE"
      ],
      "explanation": "Well-known systems and concepts behind spaced repetition—relevant to applied learning science and scheduling algorithms used in language-learning products.",
      "color": "Purple"
     }
    ],
    "recommendations": [
     {
      "title": "Tepper adds Dr. Ben Collier to teach Business Analytics (Poets&Quants, Jan 10, 2025)",
      "url": "https://poetsandquants.com/2025/01/10/meet-carnegie-mellon-teppers-mba-class-of-2026/2/",
      "type": "article"
     },
     {
      "title": "NumPy 2.x roadmap and releases (NumPy News, 2024–2025)",
      "url": "https://numpy.org/news/",
      "type": "article"
     },
     {
      "title": "scikit-learn 1.5 release highlights (2024)",
      "url": "https://scikit-learn.org/1.5/auto_examples/release_highlights/plot_release_highlights_1_5_0.html",
      "type": "article"
     },
     {
      "title": "ONC Inferno test kits: 2025 update for SMART/FHIR and US Core",
      "url": "https://fhir.healthit.gov/news/",
      "type": "article"
     },
     {
      "title": "Spaced repetition in medical education (JACR, Jan 2025)",
      "url": "https://www.sciencedirect.com/science/article/pii/S154614402400930X",
      "type": "article"
     },
     {
      "title": "Pittsburgh’s Strip District growth snapshot (Axios Pittsburgh, Aug 7, 2025)",
      "url": "https://www.axios.com/local/pittsburgh/2025/08/07/strip-district-pittsburgh-growth-report-2025",
      "type": "article"
     }
    ]
   },
   {
    "id": "ben-5",
    "title": "Model Behavior",
    "intro": "",
    "generated": {
     "model": "gpt-5",
     "ts": "2025-09-30T01:52:38.125Z",
     "player": "Ben Collier",
     "location": "Pittsburgh, PA"
    },
    "explanation": "Built around your public profile in Pittsburgh—business analytics teaching, hands-on data work, and a Duolingo connection—this set mixes classroom-ready analytics concepts, insider SQL, some app-culture Easter eggs, and one hometown category. It should feel both validating and a little tricky, with the Duolingo and SQL groups upping the challenge.",
    "categories": [
     {
      "label": "PITTSBURGH PRO TEAMS",
      "words": [
       "STEELERS",
       "PENGUINS",
       "PIRATES",
       "RIVERHOUNDS"
      ],
      "explanation": "Major Pittsburgh teams across NFL, NHL, MLB, and USL—your home turf shout-out.",
      "color": "Yellow"
     },
     {
      "label": "MODEL EVALUATION METRICS",
      "words": [
       "PRECISION",
       "RECALL",
       "ACCURACY",
       "F1-SCORE"
      ],
      "explanation": "Core performance metrics you’d teach or use in business analytics and data science.",
      "color": "Green"
     },
     {
      "label": "SQL WINDOW FUNCTIONS",
      "words": [
       "LAG",
       "LEAD",
       "RANK",
       "NTILE"
      ],
      "explanation": "Analytic SQL functions common in MBA/MSBA coursework and real-world analytics pipelines.",
      "color": "Blue"
     },
     {
      "label": "DUOLINGO LINGO",
      "words": [
       "STREAK",
       "GEMS",
       "ENERGY",
       "DUO"
      ],
      "explanation": "Gamified features and the mascot associated with the language-learning app—fun nod to your public work history.",
      "color": "Purple"
     }
    ],
    "recommendations": [
     {
      "title": "Poets&Quants: New Tepper MBA faculty—Dr. Ben Collier to teach Business Analytics (Jan 10, 2025)",
      "url": "https://poetsandquants.com/2025/01/10/meet-carnegie-mellon-teppers-mba-class-of-2026/2/",
      "type": "article"
     },
     {
      "title": "LinkedIn: Ben Collier, PhD—Tepper Business Analytics teaching-track hiring post (Spring 2025)",
      "url": "https://www.linkedin.com/posts/bcollierphd_apply-interfolio-activity-7305689417376018433-QdAz",
      "type": "article"
     },
     {
      "title": "The Verge: Duolingo is replacing Hearts with Energy (May 2025 rollout)",
      "url": "https://www.theverge.com/news/665315/duolingo-hearts-energy-system",
      "type": "article"
     },
     {
      "title": "NPR: Duo the owl ‘dies’ and is resurrected—Duolingo’s viral campaign (Feb 2025)",
      "url": "https://www.npr.org/2025/02/26/nx-s1-5309785/duolingo-owl-mascot-lives",
      "type": "article"
     },
     {
      "title": "PostgreSQL 18 Docs: Window Functions (current, Sept 2025)",
      "url": "https://www.postgresql.org/docs/current/functions-window.html",
      "type": "article"
     }
    ]
   }
  ]
 },
 {
  "id": "starwars",
  "name": "Star Wars",
  "theme": "starwars",
  "blurb": "Droids, bounty hunters, famous lines and a few traps for anyone who has seen the films more than once.",
  "disclaimer": "Fan-made trivia. Not affiliated with or endorsed by Lucasfilm or Disney. No logos, film stills or official fonts are used.",
  "puzzles": [
   {
    "id": "sw-1",
    "title": "A Galaxy of Words",
    "intro": "The grid is in turmoil. Sixteen words have scattered across the board, and only a patient player can sort them into four groups before four mistakes run out. Droids hide among bounty hunters, and a famous line or two is waiting to trip you up....",
    "explanation": "Six tiles look like droid designations, but two of them, IG-88 and 4-LOM, are also on Vader's bridge in The Empire Strikes Back, and only four bounty hunters are on the board. HOPE fits both the film titles and the famous lines; the lines need it more.",
    "categories": [
     {
      "label": "DROIDS",
      "words": [
       "R2-D2",
       "C-3PO",
       "BB-8",
       "K-2SO"
      ],
      "explanation": "The astromech, the protocol droid, the sequel trilogy's rolling sidekick, and the reprogrammed Imperial droid from Rogue One.",
      "color": "Yellow"
     },
     {
      "label": "BOUNTY HUNTERS VADER HIRES",
      "words": [
       "BOSSK",
       "DENGAR",
       "IG-88",
       "4-LOM"
      ],
      "explanation": "Lined up on the Executor's bridge in The Empire Strikes Back to hunt the Millennium Falcon. IG-88 and 4-LOM are droids too, which is the trap.",
      "color": "Green"
     },
     {
      "label": "LAST WORD OF A FILM SUBTITLE",
      "words": [
       "MENACE",
       "CLONES",
       "SITH",
       "BACK"
      ],
      "explanation": "The Phantom Menace, Attack of the Clones, Revenge of the Sith, and The Empire Strikes Back. A New Hope would fit, but HOPE is needed elsewhere.",
      "color": "Blue"
     },
     {
      "label": "LAST WORD OF A FAMOUS LINE",
      "words": [
       "TRAP",
       "TRY",
       "HOPE",
       "KNOW"
      ],
      "explanation": "\"It's a trap!\" (Ackbar), \"There is no try\" (Yoda), \"You're my only hope\" (Leia's message), and \"I know\" (Han).",
      "color": "Purple"
     }
    ]
   },
   {
    "id": "sw-2",
    "title": "The Saber Test",
    "intro": "A new board has appeared on the edge of the Outer Rim. Its colors look familiar, its creatures are hungry, and its heroes are not all where they seem. Some names are only one letter away from something else entirely....",
    "explanation": "Rey, Rose, Luke and Han all help the Resistance, which makes the Resistance group look like it has eight members. Only four names turn into new words when you add a letter in front, so those four belong together.",
    "categories": [
     {
      "label": "LIGHTSABER COLORS",
      "words": [
       "BLUE",
       "GREEN",
       "PURPLE",
       "YELLOW"
      ],
      "explanation": "Blue and green for most Jedi, purple for Mace Windu, and yellow for Rey at the very end of The Rise of Skywalker. They are also this game's four difficulty colors.",
      "color": "Yellow"
     },
     {
      "label": "CREATURES",
      "words": [
       "WAMPA",
       "RANCOR",
       "TAUNTAUN",
       "BANTHA"
      ],
      "explanation": "The ice monster on Hoth, Jabba's pit beast, the mount Han rides out into the snow, and the shaggy beasts the Tusken Raiders ride on Tatooine.",
      "color": "Green"
     },
     {
      "label": "THE RESISTANCE",
      "words": [
       "FINN",
       "POE",
       "HOLDO",
       "LEIA"
      ],
      "explanation": "The former stormtrooper, the hotshot pilot, the vice admiral of The Last Jedi, and the general who leads them all. Rey, Rose, Luke and Han fit too, which is the trap.",
      "color": "Blue"
     },
     {
      "label": "ADD A LETTER IN FRONT",
      "words": [
       "REY",
       "LUKE",
       "ROSE",
       "HAN"
      ],
      "explanation": "P+REY is PREY, F+LUKE is FLUKE, P+ROSE is PROSE, and T+HAN is THAN.",
      "color": "Purple"
     }
    ]
   },
   {
    "id": "sw-3",
    "title": "Outer Rim Run",
    "intro": "Far from the core worlds, a bounty board flickers to life. Prequel planets, dark lords, a quiet bounty hunter and his small green foundling all wait in the grid. Look up, look around, and watch your step....",
    "explanation": "MOON looks like it belongs with the planets, and SKY points straight at the Skywalkers. Both are halves of a ___WALKER word, along with SLEEP and JAY.",
    "categories": [
     {
      "label": "PREQUEL PLANETS",
      "words": [
       "NABOO",
       "KAMINO",
       "GEONOSIS",
       "MUSTAFAR"
      ],
      "explanation": "Padmé's home world, the ocean planet where the clones are grown, the droid factory world, and the lava planet where Anakin and Obi-Wan duel.",
      "color": "Yellow"
     },
     {
      "label": "DARTH ___",
      "words": [
       "VADER",
       "MAUL",
       "SIDIOUS",
       "TYRANUS"
      ],
      "explanation": "The Sith names of Anakin Skywalker, Palpatine's horned apprentice, Palpatine himself, and Count Dooku.",
      "color": "Green"
     },
     {
      "label": "THE MANDALORIAN",
      "words": [
       "GROGU",
       "BESKAR",
       "IG-11",
       "GIDEON"
      ],
      "explanation": "The foundling, the Mandalorian steel, the assassin droid turned nurse, and Moff Gideon, who hunts them.",
      "color": "Blue"
     },
     {
      "label": "___WALKER",
      "words": [
       "SKY",
       "MOON",
       "SLEEP",
       "JAY"
      ],
      "explanation": "Skywalker, moonwalker, sleepwalker and jaywalker. MOON is the trap: it looks like a place.",
      "color": "Purple"
     }
    ]
   }
  ]
 },
 {
  "id": "lotr",
  "name": "The Lord of the Rings",
  "theme": "lotr",
  "blurb": "Hobbits, rings, swords and second breakfasts, from the books and the Peter Jackson films.",
  "disclaimer": "Fan-made trivia. Not affiliated with or endorsed by the Tolkien Estate, Middle-earth Enterprises, or the film studios. The runes on this page are original doodles, not Tolkien's alphabets.",
  "puzzles": [
   {
    "id": "lotr-1",
    "title": "The Fellowship",
    "intro": "Sixteen words set out from the Shire. Four are hobbits, four are numbers, four are foes, and four are hiding something alive inside them.",
    "explanation": "BRANDYBUCK is Merry's family name, so it pulls toward the hobbits, and WORMTONGUE pulls toward the villains. Both are hiding an animal: a buck and a worm, along with the bear in TREEBEARD and the ant in PALANTIR.",
    "categories": [
     {
      "label": "HOBBITS",
      "words": [
       "FRODO",
       "SAM",
       "MERRY",
       "BILBO"
      ],
      "explanation": "The Ring-bearer, his gardener, his cousin Meriadoc, and the uncle who found the Ring in Gollum's cave. Pippin sat this one out.",
      "color": "Yellow"
     },
     {
      "label": "RINGS OF POWER, BY NUMBER",
      "words": [
       "THREE",
       "SEVEN",
       "NINE",
       "ONE"
      ],
      "explanation": "Three for the Elven-kings, seven for the Dwarf-lords, nine for Mortal Men, and one for the Dark Lord. NINE is also the number of Ringwraiths.",
      "color": "Green"
     },
     {
      "label": "FOES OF THE FELLOWSHIP",
      "words": [
       "SAURON",
       "SARUMAN",
       "SHELOB",
       "BALROG"
      ],
      "explanation": "The Dark Lord, the wizard who turned, the great spider at Cirith Ungol, and the demon of Moria. Wormtongue is a villain too, which is the trap.",
      "color": "Blue"
     },
     {
      "label": "HIDDEN ANIMALS",
      "words": [
       "TREEBEARD",
       "WORMTONGUE",
       "PALANTIR",
       "BRANDYBUCK"
      ],
      "explanation": "tree-BEAR-d, WORM-tongue, pal-ANT-ir and brandy-BUCK.",
      "color": "Purple"
     }
    ]
   },
   {
    "id": "lotr-2",
    "title": "Second Breakfast",
    "intro": "Something is cooking in the grid. There are meals to eat, blades to name, a ranger with too many names, and a hobbit with strong opinions about potatoes.",
    "explanation": "STEW looks like a hobbit meal and STICK looks like a weapon, but both come from Sam's speech about potatoes in The Two Towers film: boil 'em, mash 'em, stick 'em in a stew.",
    "categories": [
     {
      "label": "HOBBIT MEALS",
      "words": [
       "ELEVENSES",
       "LUNCHEON",
       "DINNER",
       "SUPPER"
      ],
      "explanation": "From Pippin's list in The Fellowship of the Ring film, right after second breakfast: elevenses, luncheon, afternoon tea, dinner and supper.",
      "color": "Yellow"
     },
     {
      "label": "NAMED BLADES",
      "words": [
       "STING",
       "ANDURIL",
       "GLAMDRING",
       "ORCRIST"
      ],
      "explanation": "Bilbo's and then Frodo's elven sword, Aragorn's reforged Narsil, Gandalf's sword, and Thorin's sword from The Hobbit.",
      "color": "Green"
     },
     {
      "label": "ARAGORN'S OTHER NAMES",
      "words": [
       "STRIDER",
       "ELESSAR",
       "ESTEL",
       "WINGFOOT"
      ],
      "explanation": "What the people of Bree call him, his name as king, the name he was raised under in Rivendell, and the name Éomer gives him after his long run across Rohan.",
      "color": "Blue"
     },
     {
      "label": "SAM'S POTATO RECIPE",
      "words": [
       "BOIL",
       "MASH",
       "STICK",
       "STEW"
      ],
      "explanation": "\"Po-tay-toes! Boil 'em, mash 'em, stick 'em in a stew.\" Sam, to Gollum, in The Two Towers film.",
      "color": "Purple"
     }
    ]
   },
   {
    "id": "lotr-3",
    "title": "A Long Walk to Mordor",
    "intro": "The road goes on and on. Pick out the places, the companions, the horses, and four words that close some of the most quoted lines in the films.",
    "explanation": "MORDOR looks like it belongs with the other places, but it ends Boromir's \"One does not simply walk into Mordor.\" BILL the pony looks like a companion of the Fellowship, and in a way he was, but he is a horse here.",
    "categories": [
     {
      "label": "PLACES IN MIDDLE-EARTH",
      "words": [
       "GONDOR",
       "ROHAN",
       "SHIRE",
       "RIVENDELL"
      ],
      "explanation": "The realm of Minas Tirith, the horse-lords' country, the hobbits' home, and Elrond's house in the valley.",
      "color": "Yellow"
     },
     {
      "label": "FELLOWSHIP MEMBERS, NOT HOBBITS",
      "words": [
       "GANDALF",
       "LEGOLAS",
       "GIMLI",
       "BOROMIR"
      ],
      "explanation": "The wizard, the elf, the dwarf and the man of Gondor. Aragorn is the fifth, and he is not on the board.",
      "color": "Green"
     },
     {
      "label": "HORSES AND PONIES",
      "words": [
       "SHADOWFAX",
       "BILL",
       "ASFALOTH",
       "SNOWMANE"
      ],
      "explanation": "Gandalf's horse, Sam's pony, the elf-horse that carries Frodo to the Ford of Bruinen, and King Théoden's horse.",
      "color": "Blue"
     },
     {
      "label": "LAST WORD OF A FAMOUS LINE",
      "words": [
       "PASS",
       "FOOLS",
       "AXE",
       "MORDOR"
      ],
      "explanation": "\"You shall not pass!\" and \"Fly, you fools!\" (Gandalf), \"And my axe!\" (Gimli), and \"One does not simply walk into Mordor\" (Boromir), all from The Fellowship of the Ring film.",
      "color": "Purple"
     }
    ]
   }
  ]
 },
 {
  "id": "cmu",
  "name": "Carnegie Mellon",
  "theme": "cmu",
  "blurb": "Buggy, buildings, presidents, alumni and the tech that started on a Pittsburgh hillside.",
  "disclaimer": "Made by a Carnegie Mellon faculty member for fun. Not an official university product, and no university logos or marks are used.",
  "puzzles": [
   {
    "id": "cmu-1",
    "title": "My Heart Is in the Work",
    "intro": "Andrew Carnegie's motto, and a grid full of Carnegie Mellon: a carnival weekend, the presidents on the buildings, inventions that started here, and four alumni whose names do double duty.",
    "explanation": "PORTER looks like a building (Porter Hall), and WARNER sounds like show business, but Warner is a president with a hall of his own and Porter is Billy Porter of the drama school.",
    "categories": [
     {
      "label": "SPRING CARNIVAL",
      "words": [
       "BUGGY",
       "BOOTH",
       "MOBOT",
       "MIDWAY"
      ],
      "explanation": "The buggy races through Schenley Park, the student-built booths on the Midway, and the Mobot race for small line-following robots.",
      "color": "Yellow"
     },
     {
      "label": "PRESIDENTS WITH A BUILDING",
      "words": [
       "WARNER",
       "CYERT",
       "DOHERTY",
       "COHON"
      ],
      "explanation": "Warner Hall, Cyert Hall, Doherty Hall and the Cohon University Center are named for four of the university's presidents.",
      "color": "Green"
     },
     {
      "label": "BORN AT CARNEGIE MELLON",
      "words": [
       "CAPTCHA",
       "LYCOS",
       "DUOLINGO",
       "MACH"
      ],
      "explanation": "The \"are you human?\" test, an early search engine, the language app, and the Mach kernel that macOS still builds on.",
      "color": "Blue"
     },
     {
      "label": "DRAMA ALUMNI WHOSE NAMES ARE WORDS",
      "words": [
       "HUNTER",
       "LIGHT",
       "PORTER",
       "GAD"
      ],
      "explanation": "Holly Hunter, Judith Light, Billy Porter and Josh Gad all studied in the School of Drama.",
      "color": "Purple"
     }
    ]
   },
   {
    "id": "cmu-2",
    "title": "Tartan Pride",
    "intro": "Bagpipes on the lawn, names on the buildings, the people who started artificial intelligence here, and a few words you will only hear in Pittsburgh.",
    "explanation": "NEWELL and SIMON share a building name (Newell-Simon Hall), so they tempt the buildings group, but they belong with the AI pioneers. And REDDY is a person, not \"redd up.\"",
    "categories": [
     {
      "label": "SCOTTISH SPIRIT",
      "words": [
       "SCOTTY",
       "TARTAN",
       "KILTIE",
       "BAGPIPE"
      ],
      "explanation": "The Scottish terrier mascot, the team name, the Kiltie Band, and the instrument you can earn a degree in here. Andrew Carnegie was born in Scotland.",
      "color": "Yellow"
     },
     {
      "label": "CAMPUS BUILDINGS",
      "words": [
       "WEAN",
       "HUNT",
       "GATES",
       "TEPPER"
      ],
      "explanation": "Wean Hall, Hunt Library, the Gates Hillman Centers, and the Tepper Quad.",
      "color": "Green"
     },
     {
      "label": "AI PIONEERS ON THE FACULTY",
      "words": [
       "NEWELL",
       "SIMON",
       "REDDY",
       "FAHLMAN"
      ],
      "explanation": "Allen Newell and Herbert Simon shared a Turing Award, Raj Reddy won one and was the Robotics Institute's founding director, and Scott Fahlman proposed the :-) emoticon in 1982.",
      "color": "Blue"
     },
     {
      "label": "PITTSBURGHESE",
      "words": [
       "YINZ",
       "NEBBY",
       "SLIPPY",
       "GUMBAND"
      ],
      "explanation": "You all, nosy, slippery, and a rubber band.",
      "color": "Purple"
     }
    ]
   },
   {
    "id": "cmu-3",
    "title": "Carnival Weekend",
    "intro": "Race day in Schenley Park. Find the buggy words, the alumni, the clubs in the bag, and four things that come after the word Carnegie.",
    "explanation": "Every buggy has a DRIVER, but so does every golf bag, and the buggy group has enough words without it. GOSLING is James Gosling, who earned his PhD here and went on to create Java.",
    "categories": [
     {
      "label": "GOLF CLUBS",
      "words": [
       "DRIVER",
       "IRON",
       "WEDGE",
       "PUTTER"
      ],
      "explanation": "Four clubs in the bag. DRIVER is the trap: a buggy has one too.",
      "color": "Yellow"
     },
     {
      "label": "BUGGY LINGO",
      "words": [
       "PUSHER",
       "CHUTE",
       "FREEROLL",
       "SWEEPSTAKES"
      ],
      "explanation": "Pushers run the uphill legs, the freeroll is the coast down Schenley Drive, the chute is the sharp turn at the bottom, and Sweepstakes is the race's official name.",
      "color": "Green"
     },
     {
      "label": "FAMOUS ALUMNI",
      "words": [
       "WARHOL",
       "NASH",
       "GOSLING",
       "KWOLEK"
      ],
      "explanation": "Andy Warhol (pop art), John Nash (game theory), James Gosling (the Java language), and Stephanie Kwolek (Kevlar), who studied at Margaret Morrison Carnegie College.",
      "color": "Blue"
     },
     {
      "label": "CARNEGIE ___",
      "words": [
       "HALL",
       "DELI",
       "TECH",
       "LIBRARY"
      ],
      "explanation": "Carnegie Hall in New York, the Carnegie Deli near it, Carnegie Tech (this school's name until 1967), and the Carnegie Library of Pittsburgh, next door to campus.",
      "color": "Purple"
     }
    ]
   }
  ]
 }
];
