// Checks every puzzle pack in packs/*.json and bundles them into packs/packs.js,
// which the player loads with a plain <script> tag (so the game also works from
// a file:// URL, where fetch() of a local JSON file is blocked).
//
//   node scripts/build-packs.mjs          check and write packs/packs.js
//   node scripts/build-packs.mjs --check  check only; fail if packs.js is stale
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { puzzleProblems } from '../server/validate.js';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
export const PACK_ORDER = ['ben', 'starwars', 'lotr', 'cmu'];
const THEMES = new Set(['ben', 'starwars', 'lotr', 'cmu']);

export function loadPacks() {
  const dir = path.join(ROOT, 'packs');
  const files = fs.readdirSync(dir).filter(f => f.endsWith('.json'));
  const packs = files.map(f => JSON.parse(fs.readFileSync(path.join(dir, f), 'utf8')));
  packs.sort((a, b) => rank(a.id) - rank(b.id));
  return packs;
}
function rank(id) { const i = PACK_ORDER.indexOf(id); return i === -1 ? 99 : i; }

/** Every problem across all packs, as "pack/puzzle: message" strings. */
export function packProblems(packs) {
  const out = [];
  const ids = new Set();
  for (const pack of packs) {
    for (const key of ['id', 'name', 'theme', 'blurb', 'disclaimer']) {
      if (!pack[key]) out.push(`${pack.id || '?'}: missing ${key}`);
    }
    if (!THEMES.has(pack.theme)) out.push(`${pack.id}: unknown theme ${pack.theme}`);
    if (!Array.isArray(pack.puzzles) || pack.puzzles.length < 3) out.push(`${pack.id}: needs at least 3 puzzles`);
    for (const p of pack.puzzles || []) {
      if (!p.id || ids.has(p.id)) out.push(`${pack.id}: missing or duplicate puzzle id ${p.id}`);
      ids.add(p.id);
      if (!p.title) out.push(`${pack.id}/${p.id}: missing title`);
      for (const msg of puzzleProblems(p, { strict: true })) out.push(`${pack.id}/${p.id}: ${msg}`);
    }
  }
  return out;
}

export function bundle(packs) {
  return '// Generated by scripts/build-packs.mjs from packs/*.json. Do not edit by hand.\n'
    + `window.CONNECTIONS_PACKS = ${JSON.stringify(packs, null, 1)};\n`;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const packs = loadPacks();
  const problems = packProblems(packs);
  if (problems.length) {
    console.error(problems.join('\n'));
    process.exit(1);
  }
  const out = path.join(ROOT, 'packs', 'packs.js');
  const text = bundle(packs);
  if (process.argv.includes('--check')) {
    const current = fs.existsSync(out) ? fs.readFileSync(out, 'utf8') : '';
    if (current !== text) { console.error('packs/packs.js is out of date: run node scripts/build-packs.mjs'); process.exit(1); }
    console.log('packs ok');
  } else {
    fs.writeFileSync(out, text);
    console.log(`wrote packs/packs.js: ${packs.map(p => `${p.id} (${p.puzzles.length})`).join(', ')}`);
  }
}
